import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

class AppIcons {
  static const IconData search = Symbols.search_rounded;
  static const IconData books = Symbols.auto_stories_rounded;
  static const IconData memo = Symbols.note_stack_rounded;
  static const IconData readingSpeed = Symbols.speed_rounded;
  static const IconData actions = Symbols.checklist_rounded;
  static const IconData logout = Symbols.logout_rounded;
  static const IconData calendar = Symbols.calendar_month_rounded;
  static const IconData refresh = Symbols.refresh_rounded;
  static const IconData email = Symbols.mail_rounded;
  static const IconData error = Symbols.error_circle_rounded;
  static const IconData add = Symbols.add_rounded;
  static const IconData addTask = Symbols.add_task_rounded;
  static const IconData home = Symbols.home_rounded;
  static const IconData homeFilled = Symbols.home_rounded;
  static const IconData addAlarm = Symbols.alarm_add_rounded;
  static const IconData alarmOff = Symbols.alarm_off_rounded;
  static const IconData alarm = Symbols.alarm_on_rounded;
  static const IconData timelapse = Symbols.timelapse_rounded;
  static const IconData checklist = Symbols.checklist_rounded;
  static const IconData checklistRtl = Symbols.checklist_rtl_rounded;
  static const IconData menuBook = Symbols.menu_book_rounded;
  static const IconData note = Symbols.note_alt_rounded;
  static const IconData delete = Symbols.delete_rounded;
  static const IconData deleteOutline = Symbols.delete_outline_rounded;
  static const IconData edit = Symbols.edit_rounded;
  static const IconData checkCircle = Symbols.check_circle_rounded;
  static const IconData checkCircleOutline = Symbols.check_circle_rounded;
  static const IconData close = Symbols.close_rounded;
  static const IconData chevronRight = Symbols.chevron_right_rounded;
  static const IconData chevronUp = Symbols.expand_less_rounded;
  static const IconData chevronDown = Symbols.expand_more_rounded;
  static const IconData saveAlt = Symbols.save_rounded;
  static const IconData barChart = Symbols.bar_chart_4_bars_rounded;
  static const IconData book = Symbols.menu_book_rounded;
  static const IconData bookmark = Symbols.bookmark_rounded;
  static const IconData bookmarkBorder = Symbols.bookmark_add_rounded;
  static const IconData save = Symbols.save_rounded;
  static const IconData addLibrary = Symbols.library_add_rounded;
  static const IconData check = Symbols.check_rounded;
  static const IconData noteAlt = Symbols.note_alt_rounded;
  static const IconData settings = Symbols.settings_rounded;
  static const IconData person = Symbols.person_rounded;
  static const IconData goal = Symbols.flag_circle_rounded;
  static const IconData notifications = Symbols.notifications_active_rounded;
  static const IconData darkMode = Symbols.dark_mode_rounded;
  static const IconData palette = Symbols.palette_rounded;
  static const IconData text = Symbols.text_fields_rounded;
  static const IconData export = Symbols.sim_card_download_rounded;
  static const IconData shield = Symbols.shield_person_rounded;
  static const IconData warning = Symbols.warning_rounded;
  static const IconData filter = Symbols.filter_alt_rounded;
  static const IconData manageSearch = Symbols.manage_search_rounded;
  static const IconData today = Symbols.today_rounded;
  static const IconData label = Symbols.label_rounded;
  static const IconData calendarViewWeek = Symbols.calendar_view_week_rounded;
  static const IconData calendarMonth = Symbols.calendar_month_rounded;
  static const IconData speed = Symbols.speed_rounded;
  static const IconData event = Symbols.event_rounded;
  static const IconData schedule = Symbols.schedule_rounded;
  static const IconData donutSmall = Symbols.donut_small_rounded;
  static const IconData trendingFlat = Symbols.trending_flat_rounded;
  static const IconData repeat = Symbols.repeat_rounded;
  static const IconData leaderboard = Symbols.leaderboard_rounded;
  static const IconData beachAccess = Symbols.beach_access_rounded;
  static const IconData infinity = Symbols.all_inclusive_rounded;
  static const IconData touchApp = Symbols.touch_app_rounded;
  static const IconData circle = Symbols.circle_rounded;
  static const IconData swapVert = Symbols.swap_vert_rounded;
  static const IconData arrowForward = Symbols.arrow_forward_rounded;
}

class AppIconSizes {
  static const double small = 20;
  static const double medium = 24;
  static const double large = 28;
  static const double extraLarge = 32;
}
